# numpy
**numpy** - модуль, предоставляющий пре-компилируемые функции для работы с матемиатикой, а так же массивы и методы работы с ними

In [ ]:
import numpy as np
#одномерный массив из целых чисел
a = np.array([1, 2, 3, 4, 5], int)
a[1] = 4
a

array([1, 4, 3, 4, 5])

In [ ]:
b = np.array([[1, 2, 3, 0], [1, 2, 3, 4]], int)
print(b)
b.shape

[[1 2 3 0]
 [1 2 3 4]]


(2, 4)

In [ ]:
x = np.array([1, 2, 3, 4, 5], int)
y = np.array([7, 8, 9, 0, 6], int)
print(x + y)
np.concatenate((x, y))

[ 8 10 12  4 11]


array([1, 2, 3, 4, 5, 7, 8, 9, 0, 6])

In [ ]:
x = np.array([1, 2, 3, 4, 5], int)
y = np.array([7, 8, 9, 0, 5], int)
print(x + y)
print(x * y)

[ 8 10 12  4 10]
[ 7 16 27  0 25]


In [ ]:
x = np.array([1, 2, 3, 4, 5], int)
y = np.array([7, 8, 9, 0, 5], int)
print(x.max()+y.max())
print(x.min()+y.min())

14
1


In [ ]:
x1 = np.array([[1, 2, 3, 0], [1, 6, 4, 4]], int)
x2 = np.array([[1, 2, 3, 0], [1, 2, 3, 4]], int)
print(x1)
print(x2)
print(x1 + x2)

[[1 2 3 0]
 [1 6 4 4]]
[[1 2 3 0]
 [1 2 3 4]]
[[2 4 6 0]
 [2 8 7 8]]


In [ ]:
x1 = np.array([[1, 2, 3, 0], [1, 6, 4, 4]], int)
x2 = np.array([[1, 2, 3, 0], [1, 2, 3, 4]], int)
print(x1.mean())
print(x2.mean())

2.625
2.0


##Задача 1
Найти сумму всех четных чисел от 1 до 100

In [ ]:
numbers = np.arange(2, 101, 2)
numbers.sum()

2550

Создать матрицу 5х5, заполненную случайными числами

In [ ]:
numbers = np.random.randint(5, size = (5,5))
numbers

array([[4, 3, 3, 0, 4],
       [2, 2, 1, 4, 3],
       [1, 4, 4, 0, 2],
       [4, 3, 3, 1, 1],
       [0, 1, 1, 0, 0]])